# Generated by Django 5.0 on 2023-12-10 17:14

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('aadhar_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OfferStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('property_size', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_datetime', models.DateTimeField(auto_now_add=True)),
                ('responsible_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.employee')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.property')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.client')),
                ('inspection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.client')),
                ('offer_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.offerstatus')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.property')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('listing_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.listingtype')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.property')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_document', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
                ('signed_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.client')),
                ('contract_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.contractstatus')),
                ('responsible_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.employee')),
                ('listing_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.listingtype')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.property')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPropertyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.client')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.feature')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.propertytype'),
        ),
        migrations.CreateModel(
            name='PropertyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.employee')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.property')),
                ('role_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.roletype')),
            ],
        ),
    ]
